[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/server.js"
  [build]
  functions = "netlify/functions" # Path to your Netlify Functions directory
